version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - noctx
    - nolintlint
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    forbidigo:
      forbid:
        - pattern: ^pgxpool\.New.*$
          msg: Use github.com/conduitio/conduit-connector-postgres/source/cpool.New instead.
    gocyclo:
      min-complexity: 20
    goheader:
      values:
        regexp:
          copyright-year: 20[2-9]\d
      template-path: .golangci.goheader.template
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: test/helper\.go
      - linters:
          - forbidigo
        path: source/cpool/cpool\.go
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
