name: Feature Request
description: Request a new feature.
title: "Feature: <title>"
labels: [feature, triage]
body:
  - type: textarea
    attributes:
      label: Feature description
      description: A clear and concise description of what you want to happen and what problem will this solve.
    validations:
      required: true
