// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package destination

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"key": {
			Default:     "",
			Description: "key represents the column name for the key used to identify and update existing rows.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"table": {
			Default:     "",
			Description: "table is used as the target table into which records are inserted.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"url": {
			Default:     "",
			Description: "url is the connection string for the Postgres database.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
