// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package source

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"cdcMode": {
			Default:     "auto",
			Description: "cdcMode determines how the connector should listen to changes.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"auto", "logrepl", "long_polling"}},
			},
		},
		"columns": {
			Default:     "",
			Description: "todo: reove param, Comma separated list of column names that should be included in each Record's payload.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"key": {
			Default:     "",
			Description: "todo: remove param, Column name that records should use for their `key` fields.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"logrepl.publicationName": {
			Default:     "conduitpub",
			Description: "logrepl.publicationName determines the publication name in case the connector uses logical replication to listen to changes (see CDCMode).",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"logrepl.slotName": {
			Default:     "conduitslot",
			Description: "logrepl.slotName determines the replication slot name in case the connector uses logical replication to listen to changes (see CDCMode).",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"snapshotMode": {
			Default:     "initial",
			Description: "Whether or not the plugin will take a snapshot of the entire table before starting cdc mode.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"initial", "never"}},
			},
		},
		"table": {
			Default:     "",
			Description: "List of table names to read from, separated by a comma.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"url": {
			Default:     "",
			Description: "url is the connection string for the Postgres database.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
